create database Writter;

CREATE TABLE USER(
ID_USER INT IDENTITY(10, 1)  PRIMARY KEY ,
PASSWORD VARCHAR(15) NOT NULL,
LOGIN VARCHAR(21)NOT NULL,
USERNAME NVARCHAR(15),
TYPE_USER nvarchar(5) CHECK (TYPE_USER IN('admin', 'user')) NOT NULL,
PHOTO char(1) CHECK (PHOTO IN('T', 'F'))
);

CREATE TABLE NOTE(
ID_NOTE INT IDENTITY(1,1) PRIMARY KEY,
NAME NVARCHAR(32),
NAME_USER NVARCHAR(15) NOT NULL CONSTRAINT FK_NAME_USER
							  FOREIGN KEY(NAME_USER)
							  REFERENCES USER(USERNAME),
TYPE_NOTE nvarchar(15),
STATUS varchar(12),
);

CREATE TABLE STATUS(
ID_STATUS INT IDENTITY(0, 1) PRIMARY KEY,
TYPE_STATUS VARCHAR(10) CHECK(TYPE_STATUS IN('delete', 'save')),
DATE_CREATE DATE,
TIME_CREATE TIME,
)